<template>
  <div>
    <!--?xml version="1.0" encoding="utf-8"?-->
    <!-- Generator: Adobe Illustrator 25.2.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->

    <svg version="1.1" id="layer1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 320 34" style="enable-background:new 0 0 320 34;" xml:space="preserve" width="320" height="34">
    <style type="text/css">
      .st0{fill:#FF2B06;stroke:#FF2B06;stroke-width:0.25;stroke-miterlimit:10;}
      .st1{fill:#FFFFFF;stroke:#FFFFFF;stroke-width:0.25;stroke-miterlimit:10;}
    </style>
    <g>
      <path class="st0 svg-elem-1" d="M9.2,8.5H0V0.1h28.7v8.5h-9.3v24.5H9.2V8.5z"></path>
      <path class="st0 svg-elem-2" d="M30.2,0.1H58v8.5H40.3v4.1H58v7.9H40.3v4.1H58v8.5H30.2V0.1z"></path>
      <path class="st0 svg-elem-3" d="M59.7,0.1h16.7c11,0,14.9,8.1,14.9,16.5c0,10.1-5.4,16.6-16.9,16.6H59.7L59.7,0.1L59.7,0.1z M69.9,24.6h4
        c6.3,0,7.3-5.1,7.3-8.2c0-2.1-0.7-7.9-8-7.9h-3.2L69.9,24.6L69.9,24.6z"></path>
      <path class="st0 svg-elem-4" d="M105.9,20.3l-3.1-5.1l-3,5.1h-7.5L99.4,10L92.6,0h7.5l2.8,4.9l2.8-4.9h7.5l-6.8,10l7.1,10.4H105.9z"></path>
      <path class="st1 svg-elem-5" d="M125.5,0.2v20.3c0,2.4,0.4,4.4,1.3,6c1.3,2.4,3.6,3.6,6.8,3.6c3.8,0,6.4-1.3,7.8-3.9c0.7-1.4,1.1-3.3,1.1-5.7
        V0.2h4.5v18.5c0.1,9.2-3.1,15.3-13,15.3c-9.9,0-13.1-6.1-13-15.3V0.2C120.9,0.2,125.5,0.2,125.5,0.2z"></path>
      <path class="st1 svg-elem-6" d="M177.7,0.2v3.9h-11.1v28.9h-4.5V4.1H151V0.2H177.7z"></path>
      <path class="st1 svg-elem-7" d="M178.5,25.5c0.3,3.7,2.4,5,6.4,5c1.4,0,2.8-0.3,4-1c1.1-0.6,1.8-1.7,1.7-3c0-1-0.5-1.9-1.4-2.3
        c-0.9-0.6-5.1-1.6-6.7-2c-3.9-1-7.1-2.2-7.2-6.2c-0.1-2.1,0.8-4.1,2.5-5.5c1.7-1.4,3.9-2.1,6.7-2.1c5.3-0.1,9.3,2.6,9.4,7.5h-3.8
        c-0.1-0.9-0.4-1.8-1-2.5c-1.2-1.7-6.6-2.2-8.5-0.7c-1.7,1.2-1.6,3.8,0.4,4.8c1.4,0.8,3.8,1.2,5.4,1.7c3,0.7,4.9,1.4,5.9,2
        c3.4,2.1,2.9,8-0.1,10.4c-2.8,3.2-12.6,3.1-15.2-0.1c-1.5-1.7-2.4-3.8-2.4-6L178.5,25.5z"></path>
      <path class="st1 svg-elem-8" d="M203.1,9.1V25c0,1,0.2,2.1,0.6,3c0.7,1.4,2,2.2,3.9,2.2c2.7,0,4.6-1.2,5.6-3.7c0.5-1.3,0.8-3.2,0.8-5.6V9.1h4
        v24h-3.8l0-3.5c-1.4,2.7-4.4,4.3-7.4,4.2c-3.3,0-5.6-1.2-6.9-3.4c-0.7-1.2-1-2.8-1-4.9V9.1H203.1z"></path>
      <path class="st1 svg-elem-9" d="M224.5,0.2h3.9v19.1l10.3-10.2h5.1l-9.2,8.9l9.7,15h-5.1l-7.5-12.2l-3.3,3.2v9h-3.9V0.2z"></path>
      <path class="st1 svg-elem-10" d="M251.5,9.1V25c0,1,0.2,2.1,0.6,3c0.7,1.4,2,2.2,3.9,2.2c2.7,0,4.6-1.2,5.6-3.7c0.5-1.3,0.8-3.2,0.8-5.5V9.1h4
        v24h-3.8l0.1-3.5c-0.5,0.9-1.1,1.7-1.9,2.3c-1.6,1.2-3.5,1.9-5.5,1.9c-5.6,0-7.9-3.2-7.9-8.3V9.1C247.3,9.1,251.5,9.1,251.5,9.1z"></path>
      <path class="st1 svg-elem-11" d="M272.6,0.1h3.9V12c1.7-2.2,4.4-3.6,7.2-3.5c3,0,5.4,1,7.3,3.1s2.8,5.1,2.8,9.1c0,6.7-3.3,13.3-10.4,13.2
        c-1.7,0.1-3.3-0.4-4.6-1.3c-0.9-0.7-1.7-1.5-2.4-2.5v3.1h-3.7L272.6,0.1z M288,27.7c2.8-4.5,2.6-15.7-4.8-15.6
        c-4.7,0.2-7,3.6-6.9,8.7c0,2.2,0.3,4.1,0.8,5.5c1.1,2.7,3.1,4,6,4C285.3,30.3,286.9,29.4,288,27.7z"></path>
      <path class="st1 svg-elem-12" d="M311.2,18.6c0.9-0.1,1.6-0.5,1.9-1.2c0.2-0.5,0.3-1,0.3-1.6c-0.1-3.2-2.6-3.9-5.6-3.9c-2.1,0-3.6,0.6-4.5,1.7
        c-0.5,0.6-0.8,1.6-1,2.8h-3.8c0.1-3,1-5,2.9-6.2c1.9-1.2,4.1-1.8,6.4-1.7c4.8,0.1,9.5,1.5,9.5,6.6V29c0,0.3,0.1,0.7,0.2,1
        c0.4,0.6,1.7,0.3,2.4,0.2v3c-0.5,0.2-0.9,0.2-1.4,0.3c-1.7,0.2-3.6,0-4.4-1.4c-0.4-0.7-0.6-1.4-0.7-2.2c-1,1.2-2.2,2.2-3.5,2.8
        c-1.6,0.8-3.3,1.2-5.1,1.2c-4.1,0.1-7.7-3-7.6-7.1c0-2.2,0.7-3.9,2.1-5.1c1.4-1.2,3.2-2,5.5-2.2L311.2,18.6z M302.8,29.4
        c0.9,0.7,1.9,1,3,1c1.4,0,2.8-0.3,4.1-1c3.9-1.9,3.4-4.9,3.4-8.5c-0.6,0.3-1.2,0.6-1.9,0.8c-3.5,1.1-9.8,0-9.9,5
        C301.5,27.8,301.9,28.8,302.8,29.4z"></path>
    </g>
    </svg>
  </div>
</template>

<style scoped>
/***************************************************
 * Generated by SVG Artista on 3/24/2021, 5:45:44 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

svg .svg-elem-1 {
  stroke-dashoffset: 125.4000015258789px;
  stroke-dasharray: 125.4000015258789px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
                        fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
          transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
                fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
}

svg.active .svg-elem-1 {
  stroke-dashoffset: 0;
  fill: rgb(255, 43, 6);
}

svg .svg-elem-2 {
  stroke-dashoffset: 194.6000213623047px;
  stroke-dasharray: 194.6000213623047px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.06s,
                        fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.08s;
          transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.06s,
                fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.08s;
}

svg.active .svg-elem-2 {
  stroke-dashoffset: 0;
  fill: rgb(255, 43, 6);
}

svg .svg-elem-3 {
  stroke-dashoffset: 167.29139709472656px;
  stroke-dasharray: 167.29139709472656px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s,
                        fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.16s;
          transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s,
                fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.16s;
}

svg.active .svg-elem-3 {
  stroke-dashoffset: 0;
  fill: rgb(255, 43, 6);
}

svg .svg-elem-4 {
  stroke-dashoffset: 104.66073608398438px;
  stroke-dasharray: 104.66073608398438px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.18s,
                        fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.24s;
          transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.18s,
                fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.24s;
}

svg.active .svg-elem-4 {
  stroke-dashoffset: 0;
  fill: rgb(255, 43, 6);
}

svg .svg-elem-5 {
  stroke-dashoffset: 164.2721710205078px;
  stroke-dasharray: 164.2721710205078px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s,
                        fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.32s;
          transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s,
                fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.32s;
}

svg.active .svg-elem-5 {
  stroke-dashoffset: 0;
  fill: rgb(255, 255, 255);
}

svg .svg-elem-6 {
  stroke-dashoffset: 120.99999237060547px;
  stroke-dasharray: 120.99999237060547px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.3s,
                        fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4s;
          transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.3s,
                fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4s;
}

svg.active .svg-elem-6 {
  stroke-dashoffset: 0;
  fill: rgb(255, 255, 255);
}

svg .svg-elem-7 {
  stroke-dashoffset: 138.37591552734375px;
  stroke-dasharray: 138.37591552734375px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s,
                        fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.48s;
          transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s,
                fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.48s;
}

svg.active .svg-elem-7 {
  stroke-dashoffset: 0;
  fill: rgb(255, 255, 255);
}

svg .svg-elem-8 {
  stroke-dashoffset: 128.39957427978516px;
  stroke-dasharray: 128.39957427978516px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.42s,
                        fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.56s;
          transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.42s,
                fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.56s;
}

svg.active .svg-elem-8 {
  stroke-dashoffset: 0;
  fill: rgb(255, 255, 255);
}

svg .svg-elem-9 {
  stroke-dashoffset: 144.97703552246094px;
  stroke-dasharray: 144.97703552246094px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s,
                        fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6400000000000001s;
          transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s,
                fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6400000000000001s;
}

svg.active .svg-elem-9 {
  stroke-dashoffset: 0;
  fill: rgb(255, 255, 255);
}

svg .svg-elem-10 {
  stroke-dashoffset: 128.26214599609375px;
  stroke-dasharray: 128.26214599609375px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.54s,
                        fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.72s;
          transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.54s,
                fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.72s;
}

svg.active .svg-elem-10 {
  stroke-dashoffset: 0;
  fill: rgb(255, 255, 255);
}

svg .svg-elem-11 {
  stroke-dashoffset: 162.208251953125px;
  stroke-dasharray: 162.208251953125px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s,
                        fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s;
          transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s,
                fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s;
}

svg.active .svg-elem-11 {
  stroke-dashoffset: 0;
  fill: rgb(255, 255, 255);
}

svg .svg-elem-12 {
  stroke-dashoffset: 155.98245239257812px;
  stroke-dasharray: 155.98245239257812px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6599999999999999s,
                        fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.88s;
          transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6599999999999999s,
                fill 1.8s cubic-bezier(0.47, 0, 0.745, 0.715) 1.88s;
}

svg.active .svg-elem-12 {
  stroke-dashoffset: 0;
  fill: rgb(255, 255, 255);
}

</style>